get_filename_component(TENANTBRIDGE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(TENANTBRIDGE_SRC_DIR "${TENANTBRIDGE_ROOT}/src")
set(TENANTBRIDGE_TESTS_DIR "${TENANTBRIDGE_ROOT}/tests")

file(GLOB_RECURSE TENANTBRIDGE_SOURCES CONFIGURE_DEPENDS
    "${TENANTBRIDGE_SRC_DIR}/*.cpp"
    "${TENANTBRIDGE_SRC_DIR}/*.h"
    "${TENANTBRIDGE_SRC_DIR}/*.hpp"
)

file(GLOB_RECURSE TENANTBRIDGE_COMPILE_SOURCES CONFIGURE_DEPENDS
    "${TENANTBRIDGE_SRC_DIR}/*.cpp"
)
list(FILTER TENANTBRIDGE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
list(FILTER TENANTBRIDGE_COMPILE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")

