get_filename_component(MESSAGING_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

file(GLOB_RECURSE MESSAGING_SOURCES CONFIGURE_DEPENDS
    "${MESSAGING_ROOT}/*.cpp"
    "${MESSAGING_ROOT}/*.h"
    "${MESSAGING_ROOT}/*.hpp"
)

file(GLOB_RECURSE MESSAGING_COMPILE_SOURCES CONFIGURE_DEPENDS
    "${MESSAGING_ROOT}/*.cpp"
)

list(FILTER MESSAGING_SOURCES EXCLUDE REGEX ".*/tests/.*")
list(FILTER MESSAGING_SOURCES EXCLUDE REGEX ".*/cmake/.*")
list(FILTER MESSAGING_COMPILE_SOURCES EXCLUDE REGEX ".*/tests/.*")
list(FILTER MESSAGING_COMPILE_SOURCES EXCLUDE REGEX ".*/cmake/.*")
list(FILTER MESSAGING_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
list(FILTER MESSAGING_COMPILE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
