get_filename_component(NETBRIDGE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(NETBRIDGE_SRC_DIR "${NETBRIDGE_ROOT}/src")
set(NETBRIDGE_TESTS_DIR "${NETBRIDGE_ROOT}/tests")

file(GLOB_RECURSE NETBRIDGE_SOURCES CONFIGURE_DEPENDS
    "${NETBRIDGE_SRC_DIR}/*.cpp"
    "${NETBRIDGE_SRC_DIR}/*.h"
    "${NETBRIDGE_SRC_DIR}/*.hpp"
)

file(GLOB_RECURSE NETBRIDGE_COMPILE_SOURCES CONFIGURE_DEPENDS
    "${NETBRIDGE_SRC_DIR}/*.cpp"
)
list(FILTER NETBRIDGE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
list(FILTER NETBRIDGE_COMPILE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")

